config{
    type: "view",
    schema: "covid_US",
    name: "transformed_covid_data",
    dependencies: ["${ref('covid_19_geographic_distribution_worldwide_copy')}"] 
    tags:["test"]
}

SELECT
    date, daily_confirmed,daily_deaths,confirmed_cases,
    contries_and_terriories as countries,
    geo_id,
    country_territory_code as country_code,
    pop_data_2019 as population
FROM  `covid_US.covid_19_geographic_distribution_worldwide_copy`
LIMIT 10000;