config {
    type: "view",
    schema: "covid19_data",
    name: "transformed_covid_data",
    tags:["test"]
}

SELECT
    date, daily_confirmed_cases,daily_deaths,confirmed_cases,
    countries_and_territories as countries,
    geo_id,
    country_territory_code as country_code,
    pop_data_2019 as population
FROM  `fifth-tangent-458407-f2.covid_US.covid_19_geographic_distribution_worldwide_copy`
LIMIT 10000